# Generated by Django 5.1.3 on 2024-11-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('songs', '0003_song_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='songs',
            field=models.ManyToManyField(blank=True, to='songs.song'),
        ),
    ]
